# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

fb1 = Faculty.create(id: 1, label: 'Physik und Elektrotechnik')
fb2 = Faculty.create(id: 2, label: 'Biologie und Chemie')
fb3 = Faculty.create(id: 3, label: 'Mathematik und Informatik')
fb4 = Faculty.create(id: 4, label: 'Produktionstechnik -Maschinenbau & Verfahrenstechnik-')
fb5 = Faculty.create(id: 5, label: 'Geowissenschaften')
fb6 = Faculty.create(id: 6, label: 'Rechtswissenschaft')
fb7 = Faculty.create(id: 7, label: 'Wirtschaftswissenschaft')
fb8 = Faculty.create(id: 8, label: 'Sozialwissenschaften')
fb9 = Faculty.create(id: 9, label: 'Kulturwissenschaften')
fb10 = Faculty.create(id: 10, label: 'Sprach- und Literaturwissenschaften')
fb11 = Faculty.create(id: 11, label: 'Human- und Gesundheitswissenschaften')
fb12 = Faculty.create(id: 12, label: 'Erziehungs- und Bildungswissenschaften')


Stuga.create(label: 'StugA Informatik', abbreviation: '', faculty: fb3, description: 'StugA Informatik, foobar fooo', picture: 'bug.png', website: 'https://inf.stugen.de/', email: 'inf@stugen.de', telephone: '63535', building: 'MZH', room: '1196')
Stuga.create(label: 'StugA Mathematik', abbreviation: 'Mathe', faculty: fb3, description: 'StugA Mathematik, foobar fooo', picture: 'lina.png', website: 'https://math.stugen.de/', email: 'math@stugen.de', telephone: '63536', building: 'MZH', room: '1196')
Stuga.create(label: 'StugA Digitale Medien', abbreviation: 'DM', faculty: fb3, description: 'StugA Digitale Medien, foobar fooo', picture: '', website: 'https://dm.stugen.de/', email: 'dm@stugen.de', telephone: '63535', building: 'MZH', room: '1196')
Stuga.create(label: 'StugA Wirtschaftsinformatik', abbreviation: 'WInf', faculty: fb3, description: 'StugA Wirtschaftsinformatik, foobar fooo', picture: '', website: 'https://winf.stugen.de/', email: 'winf@stugen.de', telephone: '63535', building: 'MZH', room: '1196')
# Stugeninformationen aus dem Stugen-Wiki, Stand 23.12.2017
Stuga.create(label: 'StugA Physik', abbreviation: '', faculty: fb1, description: '', picture: '', website: 'https://stuga.physik.uni-bremen.de/', email: 'stugaphy@uni-bremen.de', telephone: '62716', building: 'NW1', room: 'U1060')
Stuga.create(label: 'StugA Elektrotechnik/Informationstechnik', abbreviation: 'ET', faculty: fb1, description: '', picture: '', website: 'http://www.stugaet.uni-bremen.de/', email: 'stugaet@uni-bremen.de', telephone: '', building: 'NW1', room: 'W2080')
Stuga.create(label: 'StugA Biologie', abbreviation: '', faculty: fb2, description: '', picture: '', website: 'http://www.uni-bremen.de/stugabio.html', email: 'stugabio@uni-bremen.de', telephone: '62853', building: 'NW2', room: 'A1195')
Stuga.create(label: 'StugO Chemie', abbreviation: '', faculty: fb2, description: '', picture: '', website: 'http://www.uni-bremen.de/stugochemie.html', email: 'stugo-chemie@uni-bremen.de', telephone: '62853', building: 'NW2', room: 'A1195')
Stuga.create(label: 'StugA Berufliche Bildung', abbreviation: 'BerBil', faculty: fb4, description: '', picture: '', website: 'http://stuga-berbil.uni-bremen.de/', email: 'stuga.berbil@uni-bremen.de', telephone: '', building: 'IW', room: '1310')
Stuga.create(label: 'StugA Systems Engineering', abbreviation: 'SE', faculty: fb4, description: '', picture: '', website: 'http://syseng.stugen.de', email: 'syseng@stugen.de', telephone: '', building: 'IW', room: '1310')
Stuga.create(label: 'StugA Produktionstechnik', abbreviation: '', faculty: fb4, description: '', picture: '', website: 'http://produktionstechnik-bremen.de/', email: 'stuga@produktionstechnik-bremen.de', telephone: '4209', building: 'IW', room: '1141')
Stuga.create(label: 'StugA Wirtschaftsingenieurwesen', abbreviation: 'WIng', faculty: fb4, description: '', picture: '', website: 'https://wing.stugen.uni-bremen.de/', email: 'stugawing@uni-bremen.de', telephone: '', building: 'IW', room: '1145')
Stuga.create(label: 'StugA Geowissenschaften', abbreviation: '', faculty: fb5, description: '', picture: '', website: 'http://geowissenschaften.stugen.uni-bremen.de/', email: 'stuga@geo.uni-bremen.de', telephone: '', building: 'GEO', room: '1320')
Stuga.create(label: 'StugA Rechtswissenschaften', abbreviation: '', faculty: fb6, description: '', picture: '', website: '', email: 'stugajur@uni-bremen.de', telephone: '', building: 'GW1', room: 'B1085')
Stuga.create(label: 'StugA Hanse Law School', abbreviation: 'HLS', faculty: fb6, description: '', picture: '', website: 'https://www.uni-oldenburg.de/hanselawschool/die-hanse-law-school/studierendenvertretung/', email: 'stuga.hls@uni-bremen.de', telephone: '', building: '', room: '')
Stuga.create(label: 'StugA Wirtschaftswissenschaft', abbreviation: 'WiWi', faculty: fb7, description: '', picture: '', website: 'https://www.stugawiwi.de/', email: 'stugawiwi@uni-bremen.de', telephone: '66524', building: 'WING', room: '0.02')
Stuga.create(label: 'StugA Geographie', abbreviation: '', faculty: fb8, description: '', picture: '', website: 'http://www.geographie.uni-bremen.de/index.php?option=com_content&view=article&id=44&Itemid=49&lang=de/', email: 'stugaggr@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Geschichte', abbreviation: '', faculty: fb8, description: '', picture: '', website: 'https://ges.stugen.de/', email: 'stuges@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Politikwissenschaft', abbreviation: '', faculty: fb8, description: '', picture: '', website: 'https://politik.stugen.de/', email: 'stugapol@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Sozialpolitik', abbreviation: '', faculty: fb8, description: '', picture: '', website: 'http://sozialpolitik.stugen.de/', email: 'stuga_sp@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Soziologie', abbreviation: '', faculty: fb8, description: '', picture: '', website: 'http://soziologie.stugen.uni-bremen.de/', email: 'stugasoz@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Integrierte Europastudien', abbreviation: 'IES', faculty: fb8, description: '', picture: '', website: 'http://www.ies.uni-bremen.de/de/service/stuga.html', email: 'stugaies@uni-bremen.de', telephone: '67261', building: 'GW2', room: 'B2400')
Stuga.create(label: 'StugA Kulturwissenschaft', abbreviation: 'KuWi', faculty: fb9, description: '', picture: '', website: 'https://blogs.uni-bremen.de/kuwiahoi/', email: 'stugaqwi@uni-bremen.de', telephone: '', building: '', room: '')
Stuga.create(label: 'StugA Kunst', abbreviation: '', faculty: fb9, description: '', picture: '', website: '', email: 'kunststugahb@web.de', telephone: '', building: 'GW2', room: 'B3955')
Stuga.create(label: 'StugA Musik', abbreviation: '', faculty: fb9, description: '', picture: '', website: '', email: 'stuga-musik@uni-bremen.de', telephone: '', building: '', room: '')
Stuga.create(label: 'StugA Religion', abbreviation: '', faculty: fb9, description: '', picture: '', website: 'http://stuga.religion.uni-bremen.de/', email: 'stugarel@uni-bremen.de', telephone: '67905', building: 'SpT', room: 'C6140')
Stuga.create(label: 'StugA Philosophie', abbreviation: '', faculty: fb9, description: '', picture: '', website: 'http://www.philosophie.uni-bremen.de/studium/stuga-philosophie.html', email: 'stugaphi@uni-bremen.de', telephone: '', building: 'SFG', room: '4120')
Stuga.create(label: 'StugA Media Communications/Culture', abbreviation: 'MAC', faculty: fb9, description: '', picture: '', website: 'https://stugamac.wordpress.com/', email: 'stugamac@uni-bremen.de', telephone: '', building: '', room: '')
Stuga.create(label: 'StugA English-Speaking Cultures', abbreviation: 'ESC', faculty: fb10, description: '', picture: '', website: 'http://esc.stugen.uni-bremen.de/', email: 'stugaenglisch@uni-bremen.de', telephone: '68048', building: 'GW2', room: 'B3200')
Stuga.create(label: 'StugA Germanistik', abbreviation: '', faculty: fb10, description: '', picture: '', website: 'https://stugager.wordpress.com/', email: 'stugager@uni-bremen.de', telephone: '68048', building: 'GW2', room: 'B3200')
Stuga.create(label: 'StugA Linguistik', abbreviation: '', faculty: fb10, description: '', picture: '', website: 'http://linguistik.stugen.uni-bremen.de/', email: 'stuga-linguistik@uni-bremen.de', telephone: '68048', building: 'GW2', room: 'B3200')
Stuga.create(label: 'StugA Romanistik', abbreviation: '', faculty: fb10, description: '', picture: '', website: 'http://www.fb10.uni-bremen.de/romanistik/stuga.aspx', email: 'stugaromanistik@gmail.com', telephone: '68048', building: 'GW2', room: 'B3200')
Stuga.create(label: 'StugA Transnationale Literaturwissenschaften', abbreviation: 'TNL', faculty: fb10, description: '', picture: '', website: 'http://www.master-transnationale-literaturwissenschaft.uni-bremen.de/personen/studierende/', email: 'stugatnl@uni-bremen.de', telephone: '68048', building: 'GW2', room: 'B3200')
Stuga.create(label: 'StugA Pflegewissenschaft', abbreviation: '', faculty: fb11, description: '', picture: '', website: 'http://www.uni-bremen.de/index.php?id=13174', email: 'stuga-pflewi@uni-bremen.de', telephone: '', building: 'GRA4', room: '0070')
Stuga.create(label: 'StugA Public Health', abbreviation: '', faculty: fb11, description: '', picture: '', website: '', email: 'stugA_ph_ma@mailman.zfn.uni-bremen.de', telephone: '', building: '', room: '')
Stuga.create(label: 'Fachschaft Psychologie', abbreviation: '', faculty: fb11, description: '', picture: '', website: 'http://fspsycho-bremen.de/', email: 'fspsycho-intern@mailman.zfn.uni-bremen.de', telephone: '68538', building: 'GRA4', room: '')
Stuga.create(label: 'StugA Erziehungs- und Bildungswissenschaften', abbreviation: 'EBW', faculty: fb12, description: '', picture: '', website: 'http://www.fb12.uni-bremen.de/de/fachbereich/studierendenvertretung/stuga-ebw.html', email: 'stuga_ew@uni-bremen.de', telephone: '69722', building: 'GW2', room: 'A2270')
Stuga.create(label: 'StugA Bildungswissenschaften des Primar- und Elementarbereichs', abbreviation: 'BiPEb', faculty: fb12, description: '', picture: '', website: 'http://www.fb12.uni-bremen.de/de/fachbereich/studierendenvertretung/bipeb.html', email: 'bipeb@uni-bremen.de', telephone: '69722', building: 'GW2', room: 'A2270')
Stuga.create(label: 'StugA Gymnasium/Oberschule', abbreviation: 'GO', faculty: fb12, description: '', picture: '', website: 'http://www.fb12.uni-bremen.de/de/fachbereich/studierendenvertretung/stuga-go.html', email: 'stugago@uni-bremen.de', telephone: '69722', building: 'GW2', room: 'A2270')

